/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t doomcube_gba_mb_gba[];
extern const uint8_t doomcube_gba_mb_gba_end[];
#if __cplusplus >= 201103L
static constexpr size_t doomcube_gba_mb_gba_size=55624;
#else
static const size_t doomcube_gba_mb_gba_size=55624;
#endif
